-- =========================================================
-- SKILL_ALIAS 초기 데이터 (2026-09-30 팀 결정 — "시맨틱 매칭, 이름 일치라도")
-- 대상: SKILL.skill_name(영문 표준 표기)에 대해 한국 개발자가 실제로 흔히 쓰는 한글 표기·줄임말.
-- 전제 조건: 01_schema.sql, 09_schema_skill_alias.sql, 04_seed_skills.sql(SKILL 163건) 선행 실행
-- 기준: 확실히 널리 쓰이는 표기만 담았다 — 애매하거나 이미 짧은 약어뿐인 기술(SQL, PHP, R,
-- DNS, VPN, PKI, IAM, SIEM, TDD, OAuth 2.0 등)은 잘못된 별칭을 심느니 비워둔다. 더 필요하면
-- 이 파일에 행을 추가하면 된다(스키마 변경 없음).
-- =========================================================

SET NAMES utf8mb4;

INSERT INTO SKILL_ALIAS (skill_id, alias_name)
SELECT s.id, x.alias_name
FROM (
    SELECT 'Java' AS skill_name, '자바' AS alias_name
    UNION ALL SELECT 'Python', '파이썬'
    UNION ALL SELECT 'Python', '파이선'
    UNION ALL SELECT 'JavaScript', '자바스크립트'
    UNION ALL SELECT 'JavaScript', 'JS'
    UNION ALL SELECT 'TypeScript', '타입스크립트'
    UNION ALL SELECT 'TypeScript', 'TS'
    UNION ALL SELECT 'Go', '고랭'
    UNION ALL SELECT 'Go', 'Golang'
    UNION ALL SELECT 'Kotlin', '코틀린'
    UNION ALL SELECT 'Swift', '스위프트'
    UNION ALL SELECT 'C++', '씨쁠쁠'
    UNION ALL SELECT 'C#', '씨샵'
    UNION ALL SELECT 'Rust', '러스트'
    UNION ALL SELECT 'Ruby', '루비'
    UNION ALL SELECT 'Scala', '스칼라'
    UNION ALL SELECT 'Objective-C', '오브젝티브씨'
    UNION ALL SELECT 'Dart', '다트'
    UNION ALL SELECT 'Shell Script', '쉘스크립트'
    UNION ALL SELECT 'Shell Script', '셸스크립트'
    UNION ALL SELECT 'Perl', '펄'

    UNION ALL SELECT 'Spring', '스프링'
    UNION ALL SELECT 'Spring Boot', '스프링부트'
    UNION ALL SELECT 'Spring Boot', '스프링 부트'
    UNION ALL SELECT 'Django', '장고'
    UNION ALL SELECT 'Flask', '플라스크'
    UNION ALL SELECT 'Node.js', '노드'
    UNION ALL SELECT 'Node.js', '노드제이에스'
    UNION ALL SELECT 'Express.js', '익스프레스'
    UNION ALL SELECT 'NestJS', '네스트제이에스'
    UNION ALL SELECT 'NestJS', '네스트'
    UNION ALL SELECT 'Ruby on Rails', '레일즈'
    UNION ALL SELECT 'Ruby on Rails', 'Rails'
    UNION ALL SELECT 'Laravel', '라라벨'
    UNION ALL SELECT '.NET', '닷넷'
    UNION ALL SELECT 'ASP.NET Core', '에이에스피닷넷'

    UNION ALL SELECT 'React', '리액트'
    UNION ALL SELECT 'Vue.js', '뷰'
    UNION ALL SELECT 'Vue.js', '뷰제이에스'
    UNION ALL SELECT 'Angular', '앵귤러'
    UNION ALL SELECT 'Next.js', '넥스트'
    UNION ALL SELECT 'Next.js', '넥스트제이에스'
    UNION ALL SELECT 'Nuxt.js', '넉스트'
    UNION ALL SELECT 'Svelte', '스벨트'
    UNION ALL SELECT 'jQuery', '제이쿼리'
    UNION ALL SELECT 'Redux', '리덕스'
    UNION ALL SELECT 'HTML5', 'HTML'
    UNION ALL SELECT 'CSS3', 'CSS'
    UNION ALL SELECT 'Sass', '사스'
    UNION ALL SELECT 'Tailwind CSS', '테일윈드'
    UNION ALL SELECT 'Webpack', '웹팩'

    UNION ALL SELECT 'Android SDK', '안드로이드'
    UNION ALL SELECT 'Jetpack Compose', '제트팩 컴포즈'
    UNION ALL SELECT 'SwiftUI', '스위프트유아이'
    UNION ALL SELECT 'UIKit', '유아이킷'
    UNION ALL SELECT 'Xcode', '엑스코드'
    UNION ALL SELECT 'Android Studio', '안드로이드 스튜디오'
    UNION ALL SELECT 'React Native', '리액트 네이티브'
    UNION ALL SELECT 'Flutter', '플러터'

    UNION ALL SELECT 'MySQL', '마이에스큐엘'
    UNION ALL SELECT 'PostgreSQL', '포스트그레스'
    UNION ALL SELECT 'PostgreSQL', '포스트그레스큐엘'
    UNION ALL SELECT 'Oracle Database', '오라클'
    UNION ALL SELECT 'MS SQL Server', 'SQL Server'
    UNION ALL SELECT 'MS SQL Server', '엠에스에스큐엘서버'
    UNION ALL SELECT 'MariaDB', '마리아디비'
    UNION ALL SELECT 'MongoDB', '몽고디비'
    UNION ALL SELECT 'MongoDB', '몽고'
    UNION ALL SELECT 'Redis', '레디스'
    UNION ALL SELECT 'Cassandra', '카산드라'
    UNION ALL SELECT 'DynamoDB', '다이나모디비'
    UNION ALL SELECT 'Elasticsearch', '엘라스틱서치'
    UNION ALL SELECT 'Elasticsearch', '엘라스틱'
    UNION ALL SELECT 'Neo4j', '네오포제이'
    UNION ALL SELECT 'Amazon RDS', 'RDS'

    UNION ALL SELECT 'AWS', '아마존웹서비스'
    UNION ALL SELECT 'Google Cloud Platform', 'GCP'
    UNION ALL SELECT 'Google Cloud Platform', '지씨피'
    UNION ALL SELECT 'Microsoft Azure', '애저'
    UNION ALL SELECT 'Docker', '도커'
    UNION ALL SELECT 'Kubernetes', '쿠버네티스'
    UNION ALL SELECT 'Kubernetes', 'K8s'
    UNION ALL SELECT 'Terraform', '테라폼'
    UNION ALL SELECT 'Ansible', '앤서블'
    UNION ALL SELECT 'Jenkins', '젠킨스'
    UNION ALL SELECT 'GitHub Actions', '깃헙액션'
    UNION ALL SELECT 'Helm', '헬름'
    UNION ALL SELECT 'Nginx', '엔진엑스'
    UNION ALL SELECT 'Apache HTTP Server', '아파치'
    UNION ALL SELECT 'Prometheus', '프로메테우스'
    UNION ALL SELECT 'Grafana', '그라파나'
    UNION ALL SELECT 'ELK Stack', '엘케이스택'
    UNION ALL SELECT 'CloudFormation', '클라우드포메이션'
    UNION ALL SELECT 'Vault', '볼트'
    UNION ALL SELECT 'Load Balancing', '로드밸런싱'

    UNION ALL SELECT 'Apache Spark', '스파크'
    UNION ALL SELECT 'Apache Kafka', '카프카'
    UNION ALL SELECT 'Apache Airflow', '에어플로우'
    UNION ALL SELECT 'Hadoop', '하둡'
    UNION ALL SELECT 'Hive', '하이브'
    UNION ALL SELECT 'Apache Flink', '플링크'
    UNION ALL SELECT 'Snowflake', '스노우플레이크'
    UNION ALL SELECT 'Google BigQuery', '빅쿼리'
    UNION ALL SELECT 'Amazon Redshift', '레드시프트'
    UNION ALL SELECT 'Apache NiFi', '나이파이'

    UNION ALL SELECT 'TensorFlow', '텐서플로우'
    UNION ALL SELECT 'TensorFlow', '텐서플로'
    UNION ALL SELECT 'PyTorch', '파이토치'
    UNION ALL SELECT 'scikit-learn', '사이킷런'
    UNION ALL SELECT 'Keras', '케라스'
    UNION ALL SELECT 'Pandas', '판다스'
    UNION ALL SELECT 'NumPy', '넘파이'
    UNION ALL SELECT 'XGBoost', '엑스지부스트'
    UNION ALL SELECT 'Jupyter Notebook', '주피터'
    UNION ALL SELECT 'Hugging Face Transformers', '허깅페이스'
    UNION ALL SELECT 'Matplotlib', '맷플롯립'

    UNION ALL SELECT 'Selenium', '셀레늄'
    UNION ALL SELECT 'Appium', '어피움'
    UNION ALL SELECT 'JUnit', '제이유닛'
    UNION ALL SELECT 'pytest', '파이테스트'
    UNION ALL SELECT 'Cypress', '사이프레스'
    UNION ALL SELECT 'Postman', '포스트맨'
    UNION ALL SELECT 'Apache JMeter', '제이미터'
    UNION ALL SELECT 'TestNG', '테스트엔지'
    UNION ALL SELECT 'Playwright', '플레이라이트'

    UNION ALL SELECT 'Wireshark', '와이어샤크'
    UNION ALL SELECT 'Metasploit', '메타스플로잇'
    UNION ALL SELECT 'Burp Suite', '버프스위트'
    UNION ALL SELECT 'Nessus', '네서스'
    UNION ALL SELECT 'Nmap', '엔맵'
    UNION ALL SELECT 'Snort', '스노트'
    UNION ALL SELECT 'Kali Linux', '칼리리눅스'

    UNION ALL SELECT 'Linux', '리눅스'
    UNION ALL SELECT 'Windows Server', '윈도우서버'
    UNION ALL SELECT 'Cisco IOS', '시스코 IOS'
    UNION ALL SELECT 'Bash', '배시'
    UNION ALL SELECT 'PowerShell', '파워쉘'
    UNION ALL SELECT 'PowerShell', '파워셸'
    UNION ALL SELECT 'VMware', '브이엠웨어'
    UNION ALL SELECT 'Zabbix', '자빅스'

    UNION ALL SELECT 'Git', '깃'
    UNION ALL SELECT 'GitHub', '깃헙'
    UNION ALL SELECT 'GitHub', '깃허브'
    UNION ALL SELECT 'GitLab', '깃랩'
    UNION ALL SELECT 'Jira', '지라'
    UNION ALL SELECT 'Confluence', '컨플루언스'
    UNION ALL SELECT 'GraphQL', '그래프큐엘'
    UNION ALL SELECT 'REST API', '레스트API'
    UNION ALL SELECT 'gRPC', '지알피씨'
    UNION ALL SELECT 'Microservices Architecture', '마이크로서비스'
    UNION ALL SELECT 'RabbitMQ', '래빗엠큐'
    UNION ALL SELECT 'WebSocket', '웹소켓'
    UNION ALL SELECT 'Design Patterns', '디자인패턴'
    UNION ALL SELECT 'Agile/Scrum', '애자일'
    UNION ALL SELECT 'Agile/Scrum', '스크럼'
    UNION ALL SELECT 'Unit Testing', '유닛테스트'
    UNION ALL SELECT 'Figma', '피그마'
    UNION ALL SELECT 'Sketch', '스케치'
    UNION ALL SELECT 'Adobe XD', '어도비엑스디'
    UNION ALL SELECT 'Zeplin', '제플린'
    UNION ALL SELECT 'Wireframing', '와이어프레이밍'
    UNION ALL SELECT 'Prototyping', '프로토타이핑'
    UNION ALL SELECT 'Design System', '디자인시스템'
) AS x
JOIN SKILL s ON s.skill_name = x.skill_name;
